/**
 * Created by max on 22.05.26.
 *
 * @file Engine.h
 * @brief Declaration of the Engine class.
 */

#ifndef UNTITLED_ENGINE_H
#define UNTITLED_ENGINE_H

#if defined(__INTELLISENSE__) || !defined(USE_CPP20_MODULES)
#include <vulkan/vulkan_raii.hpp>
#else
import vulkan_hpp;
#endif
#define GLFW_INCLUDE_VULKAN

#include <GLFW/glfw3.h>
#include "../settings/Settings.h"

/**
 * @brief Central engine controller.
 *
 * Responsible for initializing and managing the application's
 * window system (GLFW) and Vulkan context. It handles the engine
 * startup sequence, main loop execution, and resource initialization.
 */
class Engine
{
public:
    /**
     * @brief Starts the engine.
     *
     * Initializes all required subsystems, creates the Vulkan instance,
     * and enters the main application loop.
     */
    void run();

private:
    /// Engine configuration settings.
    Settings settings;

    /// Main GLFW window.
    GLFWwindow* glfwWindowInstance = nullptr;

    /// Vulkan RAII context used for instance creation and enumeration.
    vk::raii::Context vulkanContext;

    /// Primary Vulkan instance.
    vk::raii::Instance vulkanInstance = nullptr;

    /// Validation layers enabled in debug mode.
    const std::vector<char const*> vulkanValidationLayers = {"VK_LAYER_KHRONOS_validation"};

    /**
     * @brief Executes the main application loop.
     *
     * Processes window events and repeatedly updates and renders the
     * application until the window is closed.
     */
    void mainLoop() const;

    /**
     * @brief Initializes GLFW and creates the application window.
     *
     * Configures GLFW for Vulkan usage, creates the main window,
     * and registers all required callbacks.
     *
     * @throws std::runtime_error If GLFW initialization or window creation fails.
     */
    void initGLFW();

    /**
     * @brief Callback invoked when the framebuffer size changes.
     *
     * Updates the engine's stored window dimensions whenever the
     * operating system reports a resize event.
     *
     * @param window GLFW window that triggered the event.
     * @param width New framebuffer width in pixels.
     * @param height New framebuffer height in pixels.
     */
    static void framebufferResizeCallback(GLFWwindow* window, int width, int height);

    /**
     * @brief Vulkan validation layer callback.
     *
     * Receives diagnostic messages generated by Vulkan validation layers
     * and forwards them to the application's logging system.
     *
     * @param severity Severity of the validation message.
     * @param type Category of the validation message.
     * @param pCallbackData Additional information about the message.
     * @param pUserData Optional user-defined data pointer.
     *
     * @return vk::False to indicate that Vulkan should continue execution.
     */
    static VKAPI_ATTR vk::Bool32 VKAPI_CALL debugCallback(vk::DebugUtilsMessageSeverityFlagBitsEXT severity,
                                                          vk::DebugUtilsMessageTypeFlagsEXT type,
                                                          const vk::DebugUtilsMessengerCallbackDataEXT* pCallbackData,
                                                          void* pUserData);

    /**
     * @brief Creates and configures the Vulkan instance.
     *
     * Verifies that all required validation layers and instance extensions
     * are available, constructs the Vulkan instance creation information,
     * and creates the Vulkan instance.
     *
     * @throws std::runtime_error If a required layer or extension is not supported.
     */
    void initVulkanInstance();

    /**
     * @brief Retrieves all required Vulkan instance extensions.
     *
     * Collects the extensions required by GLFW and optionally adds
     * debugging extensions when validation is enabled.
     *
     * @return List of required Vulkan instance extension names.
     */
    [[nodiscard]] std::vector<const char*> getRequiredInstanceExtensions() const;
    // void initVulkanSurface();
    // void initVulkanPhysicalDevice();
    // void initVulkanLogicalDevice();
    // void initVulkanSwapChain();
    // void initVulkanRenderPass();
    // void initVulkanPipeline();
    // void initVulkanCommandPool();
    // void initVulkanCommandBuffer();
};

#endif // UNTITLED_ENGINE_H
